### ISSUE TITLE
ST: Implementar endpoint busca de produtos pelo nome

### ISSUE THREAD

**Issue by Breno-Moura** [TudoDigital/Dynamics#91]
Criar um endpoint na controller "Produto" onde eu consiga colocar o nome do produto e buscá-lo.

Ex Query:
| Using Java | Using SQL |
|-------------------|-----------------|
| Select * from produto p where p.Descricao LIKE '%'+@QueryParam+'%'; | select * from produto p where p.descricao like '%cadeira%'; |

**Comment by rtrevizoli** [comment]
Estou cancelando essa atividade, pois a funcionalidade foi implementada através de mecanismo front-end
