### ISSUE TITLE
ST: Criar tela de consulta de produtos

### ISSUE THREAD

**Issue by Breno-Moura** [TudoDigital/Dynamics#99]
Criar uma tela em HTML/CSS que tenha a possibilidade de visualizar todos os produtos.

OBS: Obrigatório colocar uma barra de pesquisa em cima para podermos pesquisar os produtos pelo nome.

**Comment by rtrevizoli** [comment]
Para atendimento da solicitação, foi aberto PR para:

Backend: https://github.com/TudoDigital/backend-quarkus/pull/10
Frontend: https://github.com/TudoDigital/frontend-vuejs/pull/7

**Comment by rtrevizoli** [comment]
Aguardando finalização do PR para encerrar a atividade

**Comment by rtrevizoli** [comment]
Fechando issue, visto que PR foi aprovado e mergeado.
